parameters:
#    yanyabo_symfony.example.class: Yanyabo\SymfonyBundle\Example

services:
    yanyabo_symfony.twig.view_extension:
        class: Yanyabo\SymfonyBundle\Twig\ViewExtension
        arguments: 
            - "@service_container"
        tags:
            - { name: twig.extension }
